#!/usr/bin/env bash
# creates a pid file and outputs different message upon signal
Exiter()
{
echo "I hate the kill command"
kill $(pgrep -F /var/run/myscript.pid)
rm -rf /var/run/myscript.pid
}
echo $BASHPID > /var/run/myscript.pid
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "Exiter()" SIGQUIT SIGTERM
while :
do
echo "To infinity and beyond"
sleep 2
done
