#!/usr/bin/env bash
# creates a pid file and outputs different message upon signal
# shellcheck disable=SC2009

Exiter()
{
pkill -F /var/run/myscript.pid
rm /var/run/myscript.pid
}
Exiter1()
{
echo "I hate the kill command"
pkill -F /var/run/myscript.pid
rm /var/run/myscript.pid
}
echo $BASHPID > /var/run/myscript.pid
trap Exiter1 SIGTERM
trap "echo Y U no love me?!" SIGINT
trap Exiter SIGQUIT
while :
do
echo "To infinity and beyond"
sleep 2
done
