#!/usr/bin/env bash
# displays best school 6 times bad luck and good luck one time
i=1
while [ $i -le 10 ]
do
((i++))
if [[ "$i" == '5' ]]; then
echo bad luck
elif [[ "$i" == '9' ]]; then
echo good luck
else
echo Best School
fi
done
